name: Keep Hugging Face Space Alive

on:
  schedule:
    # Запускать каждые 30 минут. '*' означает "любой". '*/30' означает "каждые 30".
    # Формат: минута час день месяц день_недели
    - cron: '*/30 * * * *'
  workflow_dispatch: # Это позволяет запускать workflow вручную из вкладки Actions на GitHub

jobs:
  ping_space:
    runs-on: ubuntu-latest # Использовать последнюю версию Ubuntu в качестве среды выполнения
    steps:
      - name: Ping the Space URL
        # Используем curl для отправки GET-запроса.
        # --fail заставит шаг завершиться с ошибкой, если HTTP статус не 2xx (успешный).
        # URL берется из секрета репозитория для безопасности.
        run: curl --fail "${{ secrets.HF_SPACE_URL }}" || echo "Ping failed but continuing..."
        # Добавлено '|| echo ...' чтобы воркфлоу не падал полностью, если пинг не удался,
        # но вы увидите ошибку в логах шага. Можете убрать '|| echo ...', если хотите, чтобы он падал.

